version: '3'

services:
  jenkins-one:
    image: jenkins/jenkins
    container_name: jenkins-one
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins-exec:
    image: jenkins/jenkins
    container_name: jenkins-exec
    volumes:
      - jenkins-data:/var/jenkins_home

volumes:
  jenkins-data:

