AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test Dynamo Table
Resources:
  Mydynamosam:
    Type: AWS::Serverless:SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughout:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
