apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jenkins
    spec:
      containers:
      - env:
        - name: JENKINS_HOST_HOME
          value: /data/jenkins
        image: digital38/jenkins:latest
        name: jenkins
        ports:
        - containerPort: 8080
        - containerPort: 5000
        - containerPort: 50000
        resources: {}
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-claim0
        - mountPath: /var/run/docker.sock
          name: jenkins-claim1
      restartPolicy: Always
      volumes:
      - name: jenkins-claim0
        persistentVolumeClaim:
          claimName: jenkins-claim0
      - name: jenkins-claim1
        persistentVolumeClaim:
          claimName: jenkins-claim1
status: {}
