version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "helloworld-app"
s3_bucket = ""
s3_prefix = "helloworld-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
