apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-world
spec:
  replicas: 5
  selector:
    app: hello-world
  template:
    metadata:
      name: hello-world
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nigelpoulton/pluralsight-docker-ci
        ports:
        - containerPort: 8080